# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:01
from __future__ import unicode_literals
import requests as requests

from django.db import migrations, models

def fowards_func(apps, schema_editor):
    r = requests.get("https://restcountries.eu/rest/v1/all")
    r.json()
    paises = apps.get_model("ubigeo","Pais")
    db_alias = schema_editor.connection.alias
    for pais in r.json():
        paises.objects.using(db_alias).bulk_create([
            paises(nombre=pais["name"], codigo=pais["alpha2Code"])
        ])

def reverse_func(apps, schema_editor):
    r = requests.get("https://restcountries.eu/rest/v1/all")
    paises = apps.get_model("ubigeo", "Pais")
    db_alias = schema_editor.connection.alias
    for pais in r.json():
        paises.objects.using(db_alias).filter([
            paises(nombre=pais["name"], codigo=pais["alpha2Code"]).delete()
        ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código de País')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.RunPython(fowards_func, reverse_func),
    ]
