# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Ubicación')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de la Ubicación')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud de la Ubicación')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud de la Ubicación')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Pais', verbose_name='País')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'verbose_name': 'Evento',
            },
        ),
    ]
